export const RouterLinks = {
  LOGIN: "/login",
  REGISTER: "/register",
  HOME_PAGE: "/",
  THONG_KE_TIME:"/thong-ke/thong-ke-time",
  THONG_KE_COUNT:"/thong-ke/thong-ke-count",
  THEM_THU_CONG:"/them/them-thu-cong",
  KIEM_TRA_WEBSITE:"/kiem-tra/website",
  KIEM_TRA__ONE_WEBSITE:"/kiem-tra/website-one",
  HOI_DAP: "/hoi/chatbox",
  MTA_1: "/mta/web1" ,
  MTA_2: "/mta/web2" ,
  VIENKHQS_1: "/vkhqs/web1" ,
  VIENKHQS_2: "/vkhqs/web2" ,
};
